-- ============================================================
-- Unified record indexing + storage field alignment
-- ============================================================

-- ESL lesson metadata for stable retrieval and filtering
alter table if exists esl_lessons
    add column if not exists curriculum_id text,
    add column if not exists unit_number int,
    add column if not exists lesson_index int;

-- Nature tables: align to content_data contract
alter table if exists lesson_plans
    add column if not exists description text,
    add column if not exists content_data jsonb;

alter table if exists curricula
    add column if not exists description text,
    add column if not exists content_data jsonb;

-- Compatibility columns for legacy payload layouts
alter table if exists lesson_plans
    add column if not exists plan_data jsonb,
    add column if not exists cover_image text,
    add column if not exists mode text;

alter table if exists curricula
    add column if not exists curriculum_data jsonb,
    add column if not exists params_data jsonb,
    add column if not exists language text;

-- Cross-app unified index table
create table if not exists record_index (
    id bigint generated by default as identity primary key,
    record_id text not null,
    app_id text not null,
    record_type text not null,
    owner_id uuid not null references auth.users(id) on delete cascade,
    title text not null,
    searchable_text text not null default '',
    textbook_level_key text,
    cefr text,
    curriculum_id text,
    unit_number int,
    tags text[] default '{}',
    quality_status text default 'unknown',
    updated_at timestamptz default now(),
    unique (record_id, owner_id)
);

create index if not exists idx_record_index_owner_updated
    on record_index(owner_id, updated_at desc);

create index if not exists idx_record_index_filters
    on record_index(owner_id, app_id, record_type, textbook_level_key, curriculum_id, unit_number);

create index if not exists idx_record_index_searchable_text
    on record_index using gin (to_tsvector('simple', searchable_text));

alter table record_index enable row level security;

do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'record_index'
          and policyname = 'Users manage own record_index'
    ) then
        create policy "Users manage own record_index"
            on record_index
            for all
            using (auth.uid() = owner_id)
            with check (auth.uid() = owner_id);
    end if;
end $$;
