import { useCallback } from 'react';
import PptxGenJS from 'pptxgenjs';
import { Slide } from '../types';

const INDIGO = '4F46E5';
const LIGHT_BG = 'F5F3FF';

export const usePptxExport = () => {

    const exportSlidesPptx = useCallback(async (slides: Slide[], topic: string) => {
        const pptx = new PptxGenJS();
        pptx.layout = 'LAYOUT_WIDE';
        pptx.author = 'ESL Smart Planner';
        pptx.title = topic || 'Presentation Slides';

        // -- Title Slide --
        const titleSlide = pptx.addSlide();
        titleSlide.background = { color: INDIGO };
        titleSlide.addText(topic || 'Lesson Slides', {
            x: 0.5, y: 1.5, w: '90%', h: 2,
            fontSize: 40, fontFace: 'Arial',
            color: 'FFFFFF', bold: true,
            align: 'center',
        });
        titleSlide.addText('Generated by ESL Smart Planner', {
            x: 0.5, y: 4, w: '90%', h: 0.5,
            fontSize: 14, fontFace: 'Arial',
            color: 'C7D2FE',
            align: 'center',
        });

        // -- Content Slides --
        slides.forEach((slide, idx) => {
            const s = pptx.addSlide();
            s.background = { color: 'FFFFFF' };

            // Top accent bar
            s.addShape(pptx.ShapeType.rect, {
                x: 0, y: 0, w: '100%', h: 0.08,
                fill: { color: INDIGO },
            });

            // Slide number badge
            s.addText(`${idx + 1}`, {
                x: 12, y: 0.2, w: 0.6, h: 0.6,
                fontSize: 14, fontFace: 'Arial',
                color: INDIGO, bold: true,
                align: 'center',
                shape: pptx.ShapeType.roundRect,
                fill: { color: LIGHT_BG },
                rectRadius: 0.1,
            });

            // Title
            s.addText(slide.title || `Slide ${idx + 1}`, {
                x: 0.5, y: 0.3, w: '85%', h: 0.8,
                fontSize: 28, fontFace: 'Arial',
                color: '1E1B4B', bold: true,
            });

            // Content
            s.addText(slide.content || '', {
                x: 0.5, y: 1.3, w: '90%', h: 3.5,
                fontSize: 16, fontFace: 'Arial',
                color: '374151',
                valign: 'top',
                paraSpaceAfter: 8,
            });

            // Visual description as a bottom box
            if (slide.visual) {
                s.addText(`🎨 Visual: ${slide.visual}`, {
                    x: 0.5, y: 5.2, w: '90%', h: 0.6,
                    fontSize: 11, fontFace: 'Arial',
                    color: '6B7280', italic: true,
                    fill: { color: 'F9FAFB' },
                    rectRadius: 0.05,
                });
            }

            // Layout design as note
            if (slide.layoutDesign) {
                s.addNotes(`Layout: ${slide.layoutDesign}\nVisual: ${slide.visual || ''}`);
            }
        });

        await pptx.writeFile({ fileName: `${topic || 'slides'}.pptx` });
    }, []);

    return { exportSlidesPptx };
};
